SELECT
    PRODUCT_CODE,
    o.SALES_AMOUNT* p.PRICE AS SALES
FROM PRODUCT p
JOIN (
    SELECT 
        PRODUCT_ID,
        SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE 
    GROUP BY PRODUCT_ID
    ) o
ON p.PRODUCT_ID = o.PRODUCT_ID
ORDER BY 2 DESC, 1
;


