-- 코드를 입력하세요
SELECT
    H.CAR_ID,
    CASE
        WHEN EXISTS(
            SELECT 1 
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY T 
            WHERE 
            H.CAR_ID = T.CAR_ID AND 
            '2022-10-16' BETWEEN T.START_DATE AND T.END_DATE
        ) THEN '대여중'
        ELSE '대여 가능'
    END
    AS AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
GROUP BY CAR_ID
ORDER BY 1 DESC
;
    