SELECT
    A.APNT_NO,
    P.PT_NAME,
    P.PT_NO,	
    D.MCDP_CD,	
    D.DR_NAME,	
    A.APNT_YMD
FROM
    APPOINTMENT A
JOIN PATIENT P USING (PT_NO)
JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE
A.APNT_CNCL_YMD IS NULL AND
A.APNT_YMD LIKE "2022-04-13%" AND
A.MCDP_CD LIKE 'CS'
ORDER BY A.APNT_YMD
;