SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    S - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA
LEFT JOIN
    (
        SELECT
            YEAR(DIFFERENTIATION_DATE) AS Y,
            MAX(SIZE_OF_COLONY) AS S
        FROM ECOLI_DATA
        GROUP BY 1
    ) T
ON T.Y = YEAR(DIFFERENTIATION_DATE)

ORDER BY 1, 2;