-- 코드를 입력하세요
SELECT DISTINCT
    CAR_ID
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
LEFT JOIN
    CAR_RENTAL_COMPANY_CAR C USING(CAR_ID)
WHERE
    C.CAR_TYPE LIKE '세단' AND
    MONTH(H.START_DATE) = 10
ORDER BY 1 DESC
;
    
