SELECT
ID,
FISH_NAME,
LENGTH
FROM
    (
    SELECT
        ID,
        FISH_NAME,
        LENGTH,
        RANK() OVER (PARTITION BY I.FISH_TYPE ORDER BY LENGTH DESC) AS rnk
    FROM FISH_INFO I
    LEFT JOIN FISH_NAME_INFO N
    USING (FISH_TYPE)
    ) T
WHERE rnk = 1
ORDER BY 1
;